# -*- coding: utf-8 -*-
"""booksparse.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11oNSPUMaVqnSUqe2UXxNG7kleBnECX9s
"""

import pandas as pd
#!/usr/bin/python3

#   open the file 'books.csv' as read-only as assign it the file handle 'f'
f = open('books.csv', 'r', encoding="utf-8")

#   Skip the header row, i.e. first row, by reading it and doing nothing with it
#   This line isn't needed if the header row is manually deleted from books.csv
f.readline()

# This is so we can stop after a few lines
#rowCounter = 0
with open('bookauthors.txt', 'w', encoding='utf-8') as ptr:
  authorsdata = ''
  author_id = 1
  book_id = 1
  for line in f:
      #print(line)
      cols = line.split("\t")  # split each line into a list of column values
      authors = cols[3].split(",")    # split the fourth column (authors) on commas
      cols = cols[1:3]          # only keep the 2nd and 3rd columns: isbn13, and title
      
      # create a single string by joining the columns with comma delimiters and quotes
      bookValues = '"' + '","'.join(cols) + '"'
      bookValues = '"' + str(book_id) + "\"," + bookValues 
      
      #print (bookValues)
      #print (cols)
      #print (authors)
      for auth in authors:
              # CHECK FIRST TO MAKE SURE THIS AUTHOR WASN'T ALREADY INSERTED IN THE "Authors" TABLE
              #print("INSERT INTO Authors (author_id, name) VALUES (" + str(author_id) + ",\"" + str(auth) + "\");")
              authorsdata =  str(author_id) + "\t\"" + str(auth) + "\""
              
              #print(authorsdata)
              #ptr.write(authorsdata)
              #ptr.write('\n')
              books_authors =  str(book_id) + "," + str(author_id) 
              ptr.write(books_authors)
              ptr.write('\n')
              # IF THAT author already exists in Authors table, use that author_id for "INSERT INTO Book_authors"
              #print("INSERT INTO Book_authors (book_id, author_id) VALUES (" + str(book_id) + "," + str(author_id) + ");")        
              author_id += 1  #   Increment to generate next author_id

      book_id += 1    #   Increment to generate next book_id
              #print(authorsdata)

      #rowCounter += 1
      #if(rowCounter > 10): # Stop after 10 lines
        # break
f.close()# # with open('books.csv', encoding="utf-8") as f:
print(ptr)



